
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      jdbc-url: jdbc:h2:mem:elog_personal;MODE=mysql;DB_CLOSE_ON_EXIT=FALSE

logging:
  level:
    root: debug
    com.kty.elog_personal.repository.*: debug
    com.kty.elog_personal.service.*: debug
    com.kty.elog_personal.api.*: debug
